---
kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build-push
  pull: always
  image: golang:1.14
  commands:
  - go build -v -a -o docker-demo
  environment:
    CGO_ENABLED: 0
  when:
    event:
      exclude:
      - tag

